name: "Bump version"
description: "Bump package version number automatically"
inputs:
  push_commit:
    description: 'Whether to push the bump version commit.'
    required: false
    default: false
env:
  bump_type: "patch"
  auto_push: "contains(github.event.head_commit.message, '***BUMP MAJOR***') || contains(github.event.head_commit.message, '***BUMP MINOR***') || contains(github.event.head_commit.message, '***BUMP PATCH***')"
runs:
  using: "composite"
  steps:
    - run: echo "::set-env name=bump_type::minor"
      - if: contains(github.event.head_commit.message, '***BUMP MINOR***')
    - run: echo "::set-env name=bump_type::major"
      - if: contains(github.event.head_commit.message, '***BUMP MAJOR***')
    - name: Config github user
      run: |
        git config --global user.email "idm_bamboo_user@idmod.org"
        git config --global user.name "BambooUser-IDM"
    - name: Install bump2version
      run: python -m pip install bump2version
      shell: bash
    - name: bumpversion
      run: bumpversion --allow-dirty --config-file .bump_version.cfg ${{ env.bump_type }} 
      shell: bash
    - name: Config github user
      run: |
        git config --global user.email "idm_bamboo_user@idmod.org"
        git config --global user.name "BambooUser-IDM"
    - name: Push verison update
      if: "${{ env.push_commit }} && !${{ env.auto_push }}"
      run: git push

