# This workflows will install {{ cookiecutter.library_name }} from setup-dev then run tests with curl command
#
#curl command from your cmd:
# curl -XPOST -u "username:githubPAT" -H "Accept: application/vnd.github.everest-preview+json" \
# -H "Content-Type: application/json" \
# --data "{\"event_type\": \"run_setup_dev_test\"}" \
#  https://api.github.com/repos/{{ cookiecutter.github_owner }}/{{ cookiecutter.repo_name }}/dispatches
#
# Note, this test will checkout 'dev' branch

name: "Install with setup-dev and run all test"

on:
 repository_dispatch:
  types: [run_setup_dev_test]
 pull_request:
   types: [opened, edited, reopened]

jobs:
  install-setup-dev-run-all-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          ref: dev
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: |
          sudo apt-get update
          sudo apt-get install make
          pip install black flake8
      - name: Run setup-dev
        run: |
          make setup-dev
      - name: run {{ cookiecutter.library_name }} tests
        run: |
            py.test --durations=3 -v --junitxml=test_results.xml
      - name: Upload {{ cookiecutter.library_name }} test results
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: {{ cookiecutter.library_name }}_test_results
          path: tests/test_results.xml