name: Package and test on windows
on:
  push:
  pull_request:
jobs:
  build_test_windows:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '***SKIPBUILD***')"
    strategy:
      max-parallel: 1
      matrix:
        python-version: [ '3.6' ]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Bump version
        run: python ./.github/scripts/bump_version.py --commit-msg "${{github.event.head_commit.message}}"
        shell: bash
      - name: Build and install package
        uses: ./.github/actions/build-install-package
        with:
          package_file: 'package_setup.py'
      - name: run unit tests
        run: python -m unittest discover .
        working-directory: ./tests