name: Package and test on windows
on:
  push:
  pull_request:
jobs:
  build_test_windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
        working-directory: "./{{ cookiecutter.library_name }}"
    if: "!contains(github.event.head_commit.message, '***SKIPBUILD***')"
    strategy:
      max-parallel: 1
      matrix:
        python-version: [ '3.6' ]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Bump version
        run: python "${{github.workspace}}/.github/scripts/bump_version.py" --commit-msg "${{github.event.head_commit.message}}"
      - name: Build and install package
        uses: "./.github/actions/build-install-package"
      - name: run unit tests
        run: pytest
        working-directory: "./tests"
