name: Package and test on Ubuntu
on:
  workflow_dispatch:
  push:
  pull_request:
jobs:
  build_test_ubuntu:
    runs-on: ubuntu-latest
    env: 
      working-directory: "./{{ cookiecutter.library_name }}"
    if: "!contains(github.event.head_commit.message, '***SKIPBUILD***')"
    strategy:
      max-parallel: 1
      matrix:
        python-version: [ '3.6', '3.7', '3.8' ]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Bump version
        run: python "${{github.workspace}}/.github/scripts/bump_version.py" --commit-msg "${{github.event.head_commit.message}}"
        shell: bash
        working-directory: ${{env.working-directory}}
      - name: install snappy
        run: sudo apt-get install libsnappy-dev
        shell: bash
      - name: Build and install package
        uses: "${{github.workspace}}/.github/actions/build-install-package"
        working-directory: ${{env.working-directory}}
      - name: run unit tests
        run: pytest
        working-directory: "${{env.working-directory}}/tests"
