name: Explicitly bump major/minor/patch version.
on:
  workflow_dispatch:
  push:
  pull_request:
jobs:
  bump_version:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: "./{{ cookiecutter.library_name }}"
    if: "contains(github.event.head_commit.message, '***BUMP MAJOR***') || contains(github.event.head_commit.message, '***BUMP MINOR***') || contains(github.event.head_commit.message, '***BUMP PATCH***')"
    strategy:
      max-parallel: 1
      matrix:
        python-version: [ '3.6' ]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Bump version
        run: python "${{github.workspace}}/.github/scripts/bump_version.py" --commit-msg "${{github.event.head_commit.message}}" --push-allowed

